import { CATALOG_SUBJECT_TOPIC_NAMES } from '../lib/quiz-question-bank.js';

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const SUBJECT_ICONS: Readonly<Record<string, string>> = {
  Biology: '🧬',
  Chemistry: '⚗️',
  Physics: '⚛️',
  History: '🏛️',
  Geography: '🌍',
  English: '📚',
  'A-Math': '📐',
  'E-Math': '🔢',
};

// Singapore secondary schools (mainstream, religious, madrasah, and NT/special-needs
// secondary schools), sourced from https://en.wikipedia.org/wiki/List_of_secondary_schools_in_Singapore.
// Junior colleges were excluded as they are post-secondary, not secondary, institutions.
const REAL_SCHOOL_NAMES = [
  'Admiralty Secondary School',
  'Ahmad Ibrahim Secondary School',
  'Anderson Secondary School',
  'Anglican High School',
  'Anglo-Chinese School (Barker Road)',
  'Anglo-Chinese School (Independent)',
  'Ang Mo Kio Secondary School',
  'Assumption English School',
  'Bartley Secondary School',
  'Beatty Secondary School',
  'Bedok Green Secondary School',
  'Bedok South Secondary School',
  'Bedok View Secondary School',
  'Bendemeer Secondary School',
  'Boon Lay Secondary School',
  'Bowen Secondary School',
  'Broadrick Secondary School',
  'Bukit Batok Secondary School',
  'Bukit Merah Secondary School',
  'Bukit Panjang Government High School',
  'Bukit View Secondary School',
  'Catholic High School',
  'Canberra Secondary School',
  "Cedar Girls' Secondary School",
  'Changkat Changi Secondary School',
  'CHIJ Katong Convent (Secondary)',
  'CHIJ Secondary (Toa Payoh)',
  "CHIJ St. Joseph's Convent",
  "CHIJ St. Nicholas Girls' School",
  "CHIJ St. Theresa's Convent",
  'Chua Chu Kang Secondary School',
  'Christ Church Secondary School',
  'Chung Cheng High School (Main)',
  'Chung Cheng High School (Yishun)',
  'Clementi Town Secondary School',
  'Commonwealth Secondary School',
  'Compassvale Secondary School',
  "Crescent Girls' School",
  'Damai Secondary School',
  'Deyi Secondary School',
  'Dunearn Secondary School',
  'Dunman High School',
  'Dunman Secondary School',
  'East Spring Secondary School',
  'Edgefield Secondary School',
  'Evergreen Secondary School',
  'Fairfield Methodist School (Secondary)',
  'Fuchun Secondary School',
  'Fuhua Secondary School',
  'Gan Eng Seng School',
  'Geylang Methodist School (Secondary)',
  'Greendale Secondary School',
  'Greenridge Secondary School',
  'Guangyang Secondary School',
  'Hai Sing Catholic School',
  'Hillgrove Secondary School',
  "Holy Innocents' High School",
  'Hougang Secondary School',
  'Hua Yi Secondary School',
  'Hwa Chong Institution',
  'Junyuan Secondary School',
  'Jurong Secondary School',
  'Jurong West Secondary School',
  'Jurongville Secondary School',
  'Juying Secondary School',
  'Kent Ridge Secondary School',
  'Kranji Secondary School',
  'Kuo Chuan Presbyterian Secondary School',
  'Loyang View Secondary School',
  'Manjusri Secondary School',
  'Maris Stella High School',
  'Marsiling Secondary School',
  'Mayflower Secondary School',
  'Meridian Secondary School',
  "Methodist Girls' School (Secondary)",
  'Montfort Secondary School',
  'Nan Chiau High School',
  'Nan Hua High School',
  "Nanyang Girls' High School",
  'Naval Base Secondary School',
  'New Town Secondary School',
  'Ngee Ann Secondary School',
  'North Vista Secondary School',
  'Northbrooks Secondary School',
  'Northland Secondary School',
  'NUS High School of Math and Science',
  'Orchid Park Secondary School',
  'Outram Secondary School',
  'Pasir Ris Crest Secondary School',
  'Pasir Ris Secondary School',
  "Paya Lebar Methodist Girls' School (Secondary)",
  'Pei Hwa Secondary School',
  'Peicai Secondary School',
  'Peirce Secondary School',
  'Presbyterian High School',
  'Punggol Secondary School',
  'Queenstown Secondary School',
  'Queensway Secondary School',
  "Raffles Girls' School (Secondary)",
  'Raffles Institution',
  'Regent Secondary School',
  'Riverside Secondary School',
  'River Valley High School',
  "St Andrew's School (Secondary)",
  "St. Patrick's School",
  'School of Science and Technology, Singapore',
  'School of the Arts',
  'Sembawang Secondary School',
  'Sengkang Secondary School',
  'Serangoon Garden Secondary School',
  'Serangoon Secondary School',
  "Singapore Chinese Girls' School",
  'Singapore Sports School',
  'Springfield Secondary School',
  "St. Anthony's Canossian Secondary School",
  "St. Gabriel's Secondary School",
  "St. Hilda's Secondary School",
  "St. Margaret's Secondary School",
  "St. Joseph's Institution",
  'Swiss Cottage Secondary School',
  'Tanglin Secondary School',
  'Tampines Secondary School',
  "Tanjong Katong Girls' School",
  'Tanjong Katong Secondary School',
  'Temasek Secondary School',
  'Unity Secondary School',
  'Victoria School',
  'West Spring Secondary School',
  'Westwood Secondary School',
  'Whitley Secondary School',
  'Woodgrove Secondary School',
  'Woodlands Ring Secondary School',
  'Woodlands Secondary School',
  'Xinmin Secondary School',
  'Yio Chu Kang Secondary School',
  'Yishun Secondary School',
  'Yishun Town Secondary School',
  'Yuan Ching Secondary School',
  'Yuhua Secondary School',
  'Yusof Ishak Secondary School',
  'Yuying Secondary School',
  'Zhenghua Secondary School',
  'Zhonghua Secondary School',
  'San Yu Adventist School',
  'Madrasah Aljunied Al-Islamiah',
  'Madrasah Irsyad Zuhri Al-Islamiah',
  'Madrasah Al-Arabiah Al-Islamiah',
  'Madrasah Al-Maarif Al-Islamiah',
  'Madrasah Alsagoff Al-Arabiah',
  'Madrasah Wak Tanjong Al-Islamiah',
  'Crest Secondary School',
] as const;

export const schoolSeed = REAL_SCHOOL_NAMES.map((name, index) => ({
  id: slugify(name),
  name,
  position: index,
}));

export const subjectSeed = Object.keys(CATALOG_SUBJECT_TOPIC_NAMES).map((name, index) => ({
  id: slugify(name),
  name,
  icon: SUBJECT_ICONS[name] ?? null,
  position: index,
}));

export const topicSeed = Object.entries(CATALOG_SUBJECT_TOPIC_NAMES).flatMap(
  ([, topicNames], subjectIndex) => {
    const subjectId = subjectSeed[subjectIndex]!.id;
    return topicNames.map((topicName, topicIndex) => ({
      id: `${subjectId}-${slugify(topicName)}`,
      subjectId,
      name: topicName,
      position: topicIndex,
    }));
  },
);
